### ISSUE TITLE
F-droid or apk

### ISSUE THREAD

**Issue by turguenev** [Dwynr/filen-app#14]
Hi!

First of all, great work! Thank you very much for your effort and for sharing this app. I think this is very promising and has a great future.

It would be awesome if you could add this to F-Droid to offer automatic updates or provide an apk as an alternative for those users who don't want or can't use Google Play (LineageOS or other roms).

**Comment by Dwynr** [comment]
Hi,

if demanded I can also release built APK's here on Github.

**Comment by duergrim** [comment]
+1 for f-droid

**Comment by turguenev** [comment]
> if demanded I can also release built APK's here on Github.

Thank u. I think it's a good idea to offer the apk option both on the official website and on github.

**Comment by fabianski7** [comment]
there won't be a version for f-droid? is that why this issue is closed?

**Comment by Dwynr** [comment]
> there won't be a version for f-droid? is that why this issue is closed?

We will release a version on F-Droid, but we have a tight roadmap.
I can give no ETA but I can say that it'll be soon.
For now there will be an APK with every major release.
