### ISSUE TITLE
Google Firebase Analytics

### ISSUE THREAD

**Issue by turguenev** [Dwynr/filen-app#17]
Hello, thanks again for your efforts. I checked on Exodus (analyzes applications to find trackers, https://reports.exodus-privacy.eu.org/en/reports/io.filen.app/latest/ ) that Filen for Android uses Google Firebase Analytics. Being an application in favor of the privacy of its users, I have two questions:

1. What information is sent to Google?
2. Could you create a version without Firebase and publish it on Fdroid or github (apk) ?

Thank you.

**Comment by Dwynr** [comment]
Hello,

no, our app does not use Firebase Analytics. No clue how that tool picked it up, a Google signature might be in capacitor (the crossplatform engine our app uses), but I would need to dig deeper for that.

**Comment by turguenev** [comment]
Hi. 
Could it be a false positive related to "com.google.firebase:firebase-messaging"? https://github.com/Dwynr/filen-app/blob/master/android/variables.gradle

More info: https://github.com/Exodus-Privacy/exodus/issues/429

Thanks for your efforts!
