### ISSUE TITLE
Unable to download any documents

### ISSUE THREAD

**Issue by iammeline** [Dwynr/filen-app#21]
Every time I try to download something a warning appears saying it was unable to write to the local filesystem, i tried to download some .txt .jpg .png documents and the same warning appears.

Android 10, installed from Playstore

![20210801_200444](https://user-images.githubusercontent.com/82101902/127788457-0ef2e61c-56b8-423b-a7cf-47f0df311694.jpg)

**Comment by Dwynr** [comment]
Should be fixed with the latest version.
